version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/DockerfilePhp8
    tty: true
    env_file:
      - .env
    external_links:
      - mysql
      - redis
    container_name: "${PROJECT_NAME_BUYWITHVAN}_app"
    restart: on-failure
    working_dir: /usr/src/app
    volumes:
      - ./App:/usr/src/app:delegated
      - ./Config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      APP_URL: "${NGINX_URL_FRONT_BUYWITHVAN}"
      DB_PORT: "${MYSQL_PORT}"
      PROJECT_NAME: "${PROJECT_NAME_BUYWITHVAN}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_HOST: mysql
      DB_DATABASE: "${MYSQL_DATABASE_BUYWITHVAN}"
    networks:
      - network-buywithvan
      - mysql_network-mysql
      - redis_network-redis
  nginx:
    build:
      context: .
      dockerfile: Dockerfiles/DockerfileNginx
    env_file:
      - .env
    container_name: "${PROJECT_NAME_BUYWITHVAN}_app_nginx"
    restart: on-failure
    working_dir: /usr/src/app
    volumes:
      - ./App:/usr/src/app:delegated
      - ./Config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    expose:
      - "${NGINX_PORT_EXPOSE_BUYWITHVAN}"
    ports:
      - "${NGINX_PORT_EXPOSE_BUYWITHVAN}:80"
    environment:
      NGINX_HOST: "${NGINX_URL_FRONT_BUYWITHVAN}"
      VIRTUAL_HOST: "${NGINX_URL_FRONT_BUYWITHVAN}"
      LETSENCRYPT_HOST: "${NGINX_URL_FRONT_BUYWITHVAN}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    networks:
      - network-buywithvan
      - proxy_reverse-proxy
networks:
  network-buywithvan:
    driver: bridge
  proxy_reverse-proxy:
    external: true
  mysql_network-mysql:
    external: true
  redis_network-redis:
    external: true